project:
  type: book

book:
  title: "The Physiological Blueprint: Modeling Biological Systems with Ordinary Differential Equations in R"
  author: "Matías Castillo-Aguilar"
  date: today
  sidebar:
    style: docked
    background: light
    footer: 'Made with <i class="fa-solid fa-heart" style="color: #ff0000;"></i>'
  chapters:
    - index.qmd
    - part: part_1_foundations_in_modeling_and_r.qmd
      chapters: 
        - 01-why-model-physiology.qmd
        - 02-a_gentle_introduction_to_r_for_modelers.qmd
        - 03-thinking_dynamically_rates_of_change.qmd
        - 04-building_simple_differential_equation_models.qmd
    - part: part_2_solving_simulating_and_visualizing_odes_in_r.qmd
      chapters: 
        - 05-introduction_to_the_desolve_package.qmd
        - 06-numerical_methods_for_solving_odes.qmd
        - 07-visualizing_model_dynamics.qmd
        - 08-exploring_parameter_sensitivity_and_uncertainty.qmd
    - part: part_3_modeling_specific_physiological_systems.qmd
      chapters: 
        - 09-modeling_basic_cardiovascular_dynamics.qmd
        - 10-introducing_autonomic_control_into_models.qmd
        - 11-modeling_exercise_responses.qmd
        - 12-focusing_on_cardiac_autonomic_modulation_models.qmd
    - part: part_4_advanced_concepts_and_future_directions.qmd
      chapters: 
        - 13-building_more_complex_models.qmd
        - 14-linking_models_to_data.qmd
        - 15-limitations_and_future_directions.qmd
    - references.qmd
  appendices:
    - appendix_a_r_installation_guide.qmd
    - appendix_b_glossary_of_mathematical_and_physiological_terms.qmd
    - appendix_c_solutions_or_hints_to_select_exercises.qmd
    - appendix_d_r_code_snippets_and_examples.qmd
  page-footer: 
    left: "Copyright 2025, Matías Castillo-Aguilar" 
    right: 
      - icon: github
        href: https://github.com/matcasti
      - icon: globe
        href: https://bayesically-speaking.com/ 
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0001-7291-247X

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



